// <auto-generated />
using System;
using Lektion_14_TLA_DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lektion_14_TLA_DataAccess.Migrations
{
    [DbContext(typeof(StuderendeContext))]
    partial class StuderendeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lektion_14_TLA_Business.Hold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hold");
                });

            modelBuilder.Entity("Lektion_14_TLA_Business.Studerende", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Alder")
                        .HasColumnType("int");

                    b.Property<Guid?>("HoldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Niveau")
                        .HasColumnType("int");

                    b.Property<DateTime>("StudieStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("Uddannelse")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HoldId");

                    b.ToTable("Studerende");
                });

            modelBuilder.Entity("Lektion_14_TLA_Business.Studerende", b =>
                {
                    b.HasOne("Lektion_14_TLA_Business.Hold", "Hold")
                        .WithMany("Studerende")
                        .HasForeignKey("HoldId");

                    b.Navigation("Hold");
                });

            modelBuilder.Entity("Lektion_14_TLA_Business.Hold", b =>
                {
                    b.Navigation("Studerende");
                });
#pragma warning restore 612, 618
        }
    }
}
